namespace win2tiz
{
	class KXml
	{
		public static readonly string s_kSolutionTag = "Solution";
		public static readonly string s_kSolutionPathAttr = "Path";

		public static readonly string s_kCommonGccConfigTag = "CommonGccConfig";
		public static readonly string s_kGccConfigTag = "GccConfig";

		public static readonly string s_kMacroTag = "Macro";
		public static readonly string s_kNameAttr = "Name";

		public static readonly string s_kValueAttr = "Value";
		public static readonly string s_kCommonValueAttr = "CommonValue";
		public static readonly string s_kDebugValueAttr = "DebugValue";
		public static readonly string s_kReleaseValueAttr = "ReleaseValue";

		public static readonly string s_kProjectTag = "Project";

		public static readonly string s_kUseS2GFileTag = "UseS2GFile";

		public static readonly string s_kMSVCConfigurationTag = "MSVCConfiguration";
		public static readonly string s_kMSVCConfiguration_DebugAttr = "Debug";
		public static readonly string s_kMSVCConfiguration_ReleaseAttr = "Release";

		public static readonly string s_kIgnoreTag = "Ignore";
		public static readonly string s_kFileTag = "File";
		public static readonly string s_kFilterTag = "Filter";

		public static readonly string s_kFileSpecificTag = "FileSpecific";
		public static readonly string s_kFileSpecific_CFLAGS_Attr = "CFLAGS";
		public static readonly string s_kFileSpecific_DEFINES_Attr = "DEFINES";

		public static readonly string s_kAddSourceFileToProjectTag = "AddSourceFileToProject";

		public static readonly string s_kUnityBuildsTag = "UnityBuilds";
		public static readonly string s_kAutoGeneratedTag = "AutoGenerated";
		public static readonly string s_kExcludeFileFromUnityBuildTag = "ExcludeFileFromUnityBuild";
		public static readonly string s_kUnityBuildsNumberAttr = "UnityBuildsNumber";
	}
}
